### ISSUE TITLE
BOOTSTRAP: imports to use

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/bootstrap#19]
We know we need one for git, so devs have common git functions sorted.

also:

https://github.com/mysteriumnetwork/node/blob/master/magefile.go
They use imports !

import (
	"github.com/mysteriumnetwork/go-ci/env"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/check"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/dev"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/test"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/packages"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/release"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/storage"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/util/docker"
	// mage:import
	_ "github.com/mysteriumnetwork/node/localnet"
	// mage:import
	_ "github.com/mysteriumnetwork/node/ci/test/testinstall"
)

---

**Comment by Winwisly100** [comment]
pr
