### ISSUE TITLE
Mage: FLutter

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/bootstrap#25]
@Winwisly100 I think its best you do this.

We use go-flutter because it makes it easer.

We MIGHT need to add google-flutter later because of ION.

Steps:

1. OS install. This installs the lower level stuff
- All Desktops.

2. Binaries install
- hover
- anything else.

3. go-flutter namespace ( as opposed to google-flutter that we might add later for ION)
- All the stuff that is from the main repo make file.
- https://github.com/getcouragenow/main/blob/master/client/Makefile
- DONT have to have ALL of it for now. Just enough to get going. Packaging stuff is a few bit of code that we can leave out for now.  

4. go-flu-create
- Makes a flutter project with the stuff we use.
- https://github.com/getcouragenow/main/blob/master/client/pubspec.yaml

SO at the end of this a Flutter dev with nothing on their machine can go from ZERO to a go-flutter project running.

This will make it much easier to onboard flutter devs and not have a zillions questions and bad setup and all the mess that follows.
 
---

Testers

LINUX - @Winwisly100 
WINDOWS - @winwisely111 
MAC - @winwisely99 

---

After this will have enough to do CI with Flutter using github actions.

NOTE: 
When in CI running on the github servers, the OS level setup is NOT done with mage. See the Github actions i already setup under the .githhub. 

When running on a devs machine,  Our Mage OS setup is for Desktops and does it all via scoop, brew etc to get flutter, java, android installed.

I hope this is clear. Its important

**Comment by Winwisly100** [comment]
pr
