### ISSUE TITLE
BOOTSTRAP: consolidation

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/bootstrap#35]
SO need github action to compile mage.go to a release.
- easy.
- Call it "bs"
- DEVS use this !!
- later add self updating via github release.

Stages

1. go run bs
- Bootstrap OS. 
- OS Folder stuff. (scoop, etc etc)
- Tools Folder installed. (pure golang) into gobin.
 - add gofish.
 - add server tools (minikube, skaffold) using gofish (later)
- Mage wraps everything above....
- "bs gen Make.go" later..

2. Repo
- I have the "bs" binary global.
- i run the "bs os setup", etc etc
- I run bs gen make.go" ( later )
- i have a make.go now...
- SO inside the make.go file at the top are any variable the devs needs to drive things.
 - e.g flutter namespace.
- call the variosu things i need:
 - e.g flutter build example.. "bs flutter-build-release variables"

**Comment by Winwisly100** [comment]
pr
