### ISSUE TITLE
BOOTSTRAP: i18n tool's examples need to work with the current way we do i18n in Flutter

### ISSUE THREAD

**Issue by joe-getcouragenow** [getcouragenow/bootstrap#70]
Its because it gives us an easy Test Harness where we can work on it and also try out new approaches as we need to without doing massive refactoring in the Packages repo.

Sure there is no flutter code duplication but thats life.

I would make a main and mod-01, and make them work together in the example.

Then we can clearly revisit how it works with Packages making precise refactorings.

NOTE that need to get the boilerplates up into the BS repo. But because we are in a rush on i18n we can just do this issue now anyway and clean it up to use the boilerplates later

**Comment by joe-getcouragenow** [comment]
https://github.com/getcouragenow/bootstrap/blob/master/tool/i18n/services/parse_test.go

go test will exercise it

**Comment by winwisely104** [comment]
https://github.com/getcouragenow/bootstrap/tree/master/tool/i18n/examples/i18n_example

The example explains and shows how the i18n tool is working for flutter projects. See it's README + Makefile. After running the commands you can get a good overview with git status.
