### ISSUE TITLE
BOOTSTRAP: i18n is failing on google translations

### ISSUE THREAD

**Issue by winwisely104** [getcouragenow/bootstrap#71]
To reproduce the error you do the following:

```
cd packages/mod-main/client/
make lang-gen-flu
```

> github.com/getcouragenow/bootstrap/tool/i18n/services.getTranslatedMaps(0x160562a, 0x2, 0xc000690400, 0x6, 0x8, 0xc00019d190, 0x1, 0xc0001d9ce0, 0x6, 0x6)
> 	/Users/alec/projects/getcouragenow/bootstrap/tool/i18n/services/translation.go:66 +0x5c9
> github.com/getcouragenow/bootstrap/tool/i18n/services.GenerateMultiLanguageFilesFromTemplate(0x7ffeefbff4cf, 0x52, 0x7ffeefbff483, 0x40, 0x7ffeefbff52b, 0x4, 0x1605d7f, 0x4, 0x160562a, 0x2, ...)
> 	/Users/alec/projects/getcouragenow/bootstrap/tool/i18n/services/write.go:298 +0x1b3
> github.com/getcouragenow/bootstrap/tool/i18n/cmd.glob..func1(0x1aa2ea0, 0xc00011a510, 0x0, 0x9, 0x0, 0x0)
> 	/Users/alec/projects/getcouragenow/bootstrap/tool/i18n/cmd/flutter.go:28 +0x1bd
> github.com/spf13/cobra.(*Command).execute(0x1aa2ea0, 0xc00011a480, 0x9, 0x9, 0x1aa2ea0, 0xc00011a480)
> 	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
> github.com/spf13/cobra.(*Command).ExecuteC(0x1aa33a0, 0x1042dca, 0x1a61d40, 0xc000000180)
> 	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/Users/alec/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
> github.com/getcouragenow/bootstrap/tool/i18n/cmd.Execute()
> 	/Users/alec/projects/getcouragenow/bootstrap/tool/i18n/cmd/root.go:29 +0x31
> main.main()
> 	/Users/alec/projects/getcouragenow/bootstrap/tool/i18n/main.go:6 +0x20
> make: *** [lang-gen-flu] Error 2

I tracked the bug down. The problem is that the translations are uploaded to google translate as one string with a separator ('=='). Google Translate returns the translations but sometimes messes the separator up (e.g. '==' transforms to '= =').
I have played around with different separator e.g. |  but then it was failing with another language. Maybe we do a call for each word (without separator)?

To see what i mean just log the variable "out" and "words" and count the separators, they should be equal.

https://github.com/getcouragenow/bootstrap/blob/d52a2699d9b7d94a989477f12ddf866dad14ac93/tool/i18n/services/translation.go#L34-L53

**Comment by joe-getcouragenow** [comment]
There is  golang test you can use.

**Comment by joe-getcouragenow** [comment]
https://github.com/getcouragenow/bootstrap/blob/master/tool/i18n/services/parse_test.go

**Comment by winwisely104** [comment]
This is how it is right now, green should have been translated, red is the original string:
![image](https://user-images.githubusercontent.com/61538094/81329329-a96dcf80-909e-11ea-8b7d-19a066f55779.png)

How to start the example
https://github.com/getcouragenow/bootstrap/blob/master/tool/i18n/examples/i18n_example/Makefile#L8-L11
